FROM python:3.12.0-bookworm as builder
RUN pip install poetry==1.8.3

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

COPY pyproject.toml ./
RUN touch README.md

RUN --mount=type=cache,target=$POETRY_CACHE_DIR poetry install --no-root

FROM python:3.12-slim-bookworm as runtime

ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

COPY src .

COPY tests/complete_flow_load_test.py .

COPY ./src/celery_tools/worker.sh /start-celeryworker
RUN sed -i 's/\r$//g' /start-celeryworker
RUN chmod +x /start-celeryworker

COPY ./start.sh /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start


COPY ./locust.sh /locust
RUN sed -i 's/\r$//g' /locust
RUN chmod +x /locust

RUN apt-get update
RUN apt-get install -y --no-install-recommends curl ca-certificates