apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: faust-scaler
  namespace: faust-workers
spec:
  scaleTargetRef:
    name: faust-worker
  minReplicaCount: 2
  maxReplicaCount: 10
  cooldownPeriod: 5
  pollingInterval: 10
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        topic: task_1
        consumerGroup: example
        lagThreshold: "50" # Scale when lag exceeds 1000
        # offsetResetPolicy: "latest"
    - type: kafka
      metadata:
        bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        topic: task_2
        consumerGroup: example
        lagThreshold: "30" # Scale when lag exceeds 1000
        # offsetResetPolicy: "latest"
